### ISSUE TITLE
disable ssl check on zip download. 

### ISSUE THREAD

**Issue by selul** [Codeinwp/pirate_bootstrap#3]
When trying to download the stack zip i get Peer certificate cannot be authenticated with known CA certificates 

i think we should use the curl that download the zips: 

```
curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
```

**Comment by preda-bogdan** [comment]
I'll work on it! I think that is a Windows problem. On windows you need a default CA set in wamp/xammp

**Comment by selul** [comment]
@preda-bogdan i've been able to fix it by adding those 2 lines in` rigger-class:110`

**Comment by preda-bogdan** [comment]
@selul I know, it's ssl thing i was just saying it only happens on windows if CA is not set. I'll add them in a few.
